# -*- makefile -*-
#
# This file is automatically generated by configure.
# Do not hand edit.

OSTYPE		:= darwin15.6.0
MACHINETYPE	:= x86_64
PLATFORM	:= x86_64-apple-darwin15.6.0
FULLOSTYPE	:= apple-darwin15.6.0
